//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airline2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int TicketId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> DateofJourny { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<int> Seatno { get; set; }
    }
}
